version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=water

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: water
    ports:
      - "5433:5432"  # Mapeando a porta 5432 do contêiner para a porta 5433 no host
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
